# RocketMQ Broker 配置文件
brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
deleteWhen = 04
fileReservedTime = 48
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH

# 存储路径配置到项目目录下
storePathRootDir = E:/code/train/rocketmq-data/store
storePathCommitLog = E:/code/train/rocketmq-data/store/commitlog
